### ISSUE TITLE
Esto solamente tiene sentido antes del bind. Ver #7

### ISSUE THREAD

**Issue by eze210** [andres912/Taller_TP1#14]
https://github.com/andres912/Taller_TP1/blob/c39c30b9ecd7d84573b30ee3e258c30bc14d24bb/common_socket.c#L60
https://github.com/andres912/Taller_TP1/issues/7

**Comment by andres-fernandez-fuks** [comment]
Pero lo hago sólo antes del bind! Si el connection_type es para connect, no hago nada en la función. Igual tal vez el nombre de la función podría haber sido más explícito creo.
